void refreshTimeFromRTC();
void setRTCfromNTP();
bool connectToWifi(bool waitForTimeout = true, unsigned long timeout = 500L);
void refreshAHT();
void refreshBMP();
void printTemp(bool sensor = false);
void singleClick();
void doubleClick();
void multiClick();
void longPressStart();
void longPressStop();
void duringLongPress();
void checkPower();
const unsigned short* getIcon(char icon[]);
bool tft_output(int16_t x, int16_t y, uint16_t w, uint16_t h, uint16_t* bitmap);
String getValue(HTTPClient &http, String key);
void printSplitString(String text,int maxLineSize, int xPos, int yPos);
void printSplitString2(char text[], int maxLineSize, int xPos, int yPos);
bool getFile(String url, String filename);
void handleRoot();
void handleCallbackPage();
void handleData();
bool sendDataToRDS(float tbmp, float pbmp,float taht, float haht);
bool getApiWeatherCurrent();
bool getApiWeather3HrForecast();
bool getApiWeatherDailyForecast();
unsigned long myAbs(long val);
void checkInternet();
void getPcInfo();
void drawPixelFrame(uint16_t gap);
void displayDefault(uint16_t color, uint16_t bg, bool refresh = false);
void displaySpotify();
void displayWeather(uint16_t color, uint16_t bg);
void displayOTA();
void refreshSensors();
void refreshDisplay();
void refreshSpotify();
void updateRDS();
void updateWeather();
void hourlyTask();
